### ISSUE TITLE
Tests doesn't run all at same time

### ISSUE THREAD

**Issue by camilo9020** [platanus/potassium#129]
locally is not possible run all test at same time, currently with the command `bundle exec rspec` only run one test: `spec/features/heroku_spec.rb`

**Comment by llekn** [comment]
I checked this and found that was caused by a focus on the heroku test (`fit` versus `it`).

While d6352938 fixes that, now the test suite hangs on a random place while creating a potassium project.

@blackjid @ldlsegovia any ideas?

**Comment by blackjid** [comment]
😱  good catch!

I didn't understand the problem, I see the tests passing on circleci https://circleci.com/gh/platanus/potassium/295

**Comment by llekn** [comment]
@blackjid The test suite hangs when I run it locally. But if it running ok on CircleCI maybe is a local problem. Maybe you can try it and see how it goes?

**Comment by blackjid** [comment]
For me everything worked fine locally.
Do you want to open a PR?

**Comment by ldlsegovia** [comment]
this is happening to me too
