### ISSUE TITLE
Replace FactoryGirl for FactoryBot

### ISSUE THREAD

**Issue by llekn** [platanus/potassium#154]
As https://github.com/thoughtbot/factory_bot/issues/921 changed `FactoryGirl` dependency name to `FactoryBot` new projects created with potassium fails to run `bin/setup`

**Comment by llekn** [comment]
I've just created a new project and there is a lot of messages saying:
```
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions
```

I think it is better to update the potassium to reflect the decision made by the old `factory_girl` community

**Comment by blackjid** [comment]
@ldlsegovia esto esta listo cierto?? puedes cerrar si estamos ok?
