### ISSUE TITLE
webpack-dev-server doesn't work on default install

### ISSUE THREAD

**Issue by llekn** [platanus/potassium#166]
After a clean install running `./bin/webpack/dev-server` fails because a version mismatch (https://github.com/rails/webpacker/issues/1303)

Steps to reproduce the problem:

 - Create a new project: `potassium create foo`
 - Go to project folder: `cd foo`
 - Try to run `webpack-dev-server`: `./bin/webpack-dev-server`

**Comment by rjherrera** [comment]
Using the latest potassium build from master (`rake install` from the repo folder), I tried to reproduce this issue choosing Vue and I couldn't, everything seems to work fine after a clean installation, and I'm able to run `./bin/webpack-dev-server`.

There seems to be an issue after a clean installation choosing Angular 2, but it doesn't appear to be related to the one mentioned in that issue. 

Could you try again and see if it still happens? If not we should close this and open another one for the specific issue with angular 2 (or maybe deprecate it 😬)

**Comment by llekn** [comment]
Hi young @rjherrera 

I just re-tried this and can confirm it works OK with Angular. Too bad that it still needs some manual config as the resultant `package.json` ends with an incompatible version of `core-js` that [needs to be downgraded](https://stackoverflow.com/questions/55319694/rails-webpacker-angular-polyfills-ts-error-cant-resolve-core-js-es6-refle), but it is a `rails-webpacker` (happens with a `rails new myapp --webpack=angular` too) thing so I don't think it is productive to continue with this.

I'll close this Issue as it seems resolved.

**Comment by llekn** [comment]
Ah, one last thing. In potassium keeps mentiones Angular 2 (from the time that everybody thought that  version 2 would be years among us) but it will install last stable version of Angular.io (currently 7.2.x). Maybe is time to change the name of the option?

**Comment by rjherrera** [comment]
I like the idea, but maybe we should remove the number, as it will always be the last one. Maybe we should open a new issue with this.
