### ISSUE TITLE
Add services standard with makefile

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#171]
Add a docker-compose file with the services needed to run the application.

We've been doing this on budacom succesfully. 

- docker-compose.yml: with services
- Makefile: with easy commands against the services
- .env.development: should ask for the exposed port for each service

**Comment by blackjid** [comment]
An example of the changes here https://github.com/platanus/cleaning-tracker-server/pull/182

**Comment by difernandez** [comment]
@blackjid this should be addressed in #197, no?

**Comment by blackjid** [comment]
yes!, good catch!
