### ISSUE TITLE
Run db:migrate when adding models

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#173]
After the app is bootstraped, and we have new models, like devise users or activeadmin comments, we should run the migrations so we trigger the `annotations` and the creation of the `db/schema.rb` file

**Comment by rjherrera** [comment]
I re-checked 😬 and `db:migrate` is running, but there is an issue with annotations, so I opened a new issue to address that. As this one is mainly focused on the `migrate` part, I'm closing it since the behavior is correct.
