### ISSUE TITLE
Agregar buenas prácticas para API

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/potassium#176]
Actualmente hay un PR con esto que está desactualizado

https://github.com/platanus/potassium/pull/148

Según lo que conversamos, en vez de hacer esto, deberíamos hacer una gema que incluya estas buenas prácticas y luego incluir en potassium la gema.

**Comment by ldlsegovia** [comment]
Tener en cuenta esto: https://github.com/platanus/potassium/issues/165

y que funcione también con la gema draper.

**Comment by ldlsegovia** [comment]
Esto https://github.com/platanus/potassium/issues/94 está contemplado acá.

Creo que sería bueno usar: `ActiveModelSerializers.config.adapter = :json_api`

**Comment by ldlsegovia** [comment]
Tener el cuenta el trabajo de estos PR:
https://github.com/platanus/potassium/pull/160
https://github.com/platanus/potassium/pull/159
https://github.com/platanus/potassium/pull/148

**Comment by llekn** [comment]
@ldlsegovia Propongo agregar un par de excepciones en el ApiErrorConcern que deberían "capturarse" ahí para retornar 400 al cliente y no 500, como por ejemplo, `ActionController::ParameterMissing` (así podemos descansar en `params.require(:foo)` en los controllers, por ejemplo.

Mi propuesta es:

```ruby
 module ApiErrorConcern
  extend ActiveSupport::Concern

  included do
    rescue_from "Exception" do |exception|
      logger.error exception.message
      logger.error exception.backtrace.join("\n")
      respond_api_error(:internal_server_error, message: "server_error",
                                                type: exception.class.to_s,
                                                detail: exception.message)
    end

    rescue_from "ActiveRecord::RecordNotFound" do |exception|
      respond_api_error(:not_found, message: "record_not_found",
                                    detail: exception.message)
    end

    rescue_from "ActiveModel::ForbiddenAttributesError" do |exception|
      respond_api_error(:bad_request, message: "protected_attributes",
                                      detail: exception.message)
    end

    rescue_from "ActiveRecord::RecordInvalid" do |exception|
      respond_api_error(:bad_request, message: "invalid_attributes",
                                      errors: exception.record.errors)
    end

    rescue_from 'ActionController::ParameterMissing' do |exception|
      respond_api_error(:bad_request, message: 'missing_parameters', errors: exception.message)
    end

    rescue_from 'ActionController::UnknownFormat' do
      render json: { message: 'format_not_supported' }, status: :bad_request
    end
  end

  def respond_api_error(status, error = {})
    render json: error, status: status
  end
end
```

**Comment by difernandez** [comment]
Voy a cerrar esto, ya está en potassium `power_api`
