### ISSUE TITLE
Update rack-timeout setter in puma recipe

### ISSUE THREAD

**Issue by rjherrera** [platanus/potassium#185]
In `rack_timeout`'s `0.5.0` release, legacy setters were removed (https://github.com/heroku/rack-timeout/pull/125), which made [this line](https://github.com/platanus/potassium/blob/master/lib/potassium/recipes/puma.rb#L10) not longer functional.

In order to fix it, similar to what is suggested in https://github.com/heroku/rack-timeout/issues/130, it should be changed to:

```ruby
config.middleware.insert_before Rack::Runtime, Rack::Timeout, service_timeout: (ENV["RACK_TIMEOUT"] || 10).to_i
```

**Comment by blackjid** [comment]
Great catch!

What do you think about using the environment variables support already baked into rack-timeout?

https://github.com/heroku/rack-timeout#configuring

**Comment by rjherrera** [comment]
I also saw that, and it looks cleaner. It would imply deleting that line, but I'm not sure on how to communicate this, maybe explicitly describing that expected behavior in the `README.md`?

I know that if we delete the line and the env var is not defined, it would not break, but it feels like hiding something that was explicit before. What do you think?
