### ISSUE TITLE
Run annotate when running migrate with_data

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#232]
```
Rake::Task["db:migrate:status"].enhance do
  Rake::Task["annotate_models"].invoke
end
```

Eso seria lo mas simple, pero tal vez podemos sacar ideas de aqui para agregarse lo a todos los que correspondan 

https://github.com/ctran/annotate_models/blob/develop/lib/tasks/annotate_models_migrate.rake#L7-L19

**Comment by difernandez** [comment]
@blackjid esto está agregado como parte de #227

**Comment by blackjid** [comment]
Fantastico!
