### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by mf222** [platanus/potassium#233]
Potassium doesn't use a standard way to define node version. In order to add the node engine to the `package.json` and to make the file `.node-version` to work with it, the idea is to make a ` heroku-buildpack-ruby-version` that sets the node version found in the `.node-version` file and appends it to the `package.json` engine section.

**Comment by difernandez** [comment]
@mf222 another way would be to add a `.node-version` with potasssium and just copy that value to the `package.json` when building a project. It would be simpler, but if the project later on needs to change node version it would have to change it in both files.

On the other hand, what version should we set it to? I had an issue with node 9 so I'm guessing at least 10.x

**Comment by rjherrera** [comment]
I think we should address this, it is a nice idea. I think we should add a `.node-version` to each project, alongside including it in the engines version, and we should use the latest version locked to the minor. Also we should include a potassium own `.node-version` as we use yarn as a dependency.
