### ISSUE TITLE
Api controllers should include ApiErrorConcern even in development

### ISSUE THREAD

**Issue by difernandez** [platanus/potassium#235]
The response has different formats for each environment, which makes it difficult to cover error cases correctly

**Comment by rjherrera** [comment]
@difernandez I think this goes in the right direction, but there might be something we are missing, as this behavior was intentionally introduced in https://github.com/platanus/potassium/pull/14. Maybe @ldlsegovia can enlighten us with the reasons for that.

**Comment by ldlsegovia** [comment]
It was a bad idea to change the functionality based on the environment
