### ISSUE TITLE
GitHub recipe depends on hub

### ISSUE THREAD

**Issue by rjherrera** [platanus/potassium#238]
If `hub` isn't installed in the shell where potassium is executed, the GitHub recipe will silently fail.

This behavior is somehow _expected_, as the recipe uses `hub` as a shell command, instead of a ruby command/method from a gem or dependency.

I don't know which one is the best solution, but we should evaluate using a ruby gem with similar features.

Thanks to @dacasas for helping discovering this issue.

**Comment by ldlsegovia** [comment]
@rjherrera ping
