### ISSUE TITLE
Use dash instead of underscore for project name in Makefile

### ISSUE THREAD

**Issue by rjherrera** [platanus/potassium#248]
Currently the Makefile template uses `:underscorized_app_name` to set the project's name. It is also used in the database YMLs. 

The problem is that by default docker-compose assumes _dasherized_ names, so that if by any chance a developer uses `docker-compose up` instead of `make services-up`, the only difference will be the name, and services may be different if the project name is longer than 1 word.

Another problem is that there is a docker "name scoping" convention in which words after a `_` are considered scoped services. This is useful for multi-service projects where services might look like `project_elasticsearch` or `project_postgresql`, and docker plugins like captain using that convention will automatically scope those like: `project` -> `elasticsearch`, `postgresql`.

With our naming convention, if the project name has multiple words, one might end up having this: `cool_project_elasticsearch`,  `cool_project_postgresql` which will be scoped as: `cool` -> `project_elasticsearch`, `project_postgresql`, instead of the obvious `cool_project` -> `elasticsearch`, `postgressql`. If the name was `cool-project`, the problem is gone.

My proposal is simply to change `:underscorized_app_name` for `:dasherized_app_name` in the makefile and database ymls.

Hey @blackjid, do you remember any reason for this behavior? Do you agree with this change?

**Comment by blackjid** [comment]
I don't rememeber why he chose underscores, probably that was before we started using docker and docker-compose, so it wasn't a problem back then.

I think is ok to use dashes.
