### ISSUE TITLE
Webpacker being added and installed twice

### ISSUE THREAD

**Issue by rjherrera** [platanus/potassium#252]
Webpacker is included by default in rails from 6.0.0 so the recipe repeats both the gem gathering and the `webpacker:install` generator. It isn't a major problem because it only repeats procedure and asks to override, but it should definitely be addressed.

I'm not sure how to approach this in potassium, but I know that the frontend option can be specified for rails generator like this `rails new project --webpack=vue`, and rails will automatically execute `webpacker:install:vue` as shown [here](https://github.com/rails/rails/blob/v6.0.2.1/railties/lib/rails/generators/app_base.rb#L414).

Maybe the approach could be that this recipe overrides the `options[:webpack]` value.

Maybe @difernandez and @gmq can help with this!

**Comment by difernandez** [comment]
I think the simplest solution would be to just remove the lines that gathers the webpacker gem and runs `webpacker:install`, and let the recipe explicitly call `webpacker:install:vue` like it does today.

I think the solution you propose is the ideal one but I don't know how to set options for the `rails new project` command in potassium. If it's easy we could go for that, if not I would start with the simple option, see if it works
