### ISSUE TITLE
Update ruby to 2.6.5 (or 2.7.0)

### ISSUE THREAD

**Issue by rjherrera** [platanus/potassium#254]
I tested some stuff with ruby 2.7 and it didn't work as expected, maybe because it is a bit green (end of december 2019).

But anyway, we currently have ruby 2.5.5 and we should move to one of those, the latest patch of the 2.6 version or the new 2.7 one.

**Comment by blackjid** [comment]
Nice, I would love to see this released on the rails 6 release.. at least with 2.6

**Comment by rjherrera** [comment]
The update to 2.7.0 is almost ready, but one gem we use, `sidekiq-scheduler` depends on `thwait` and `e2mmap`, which are gems that are no longer bundled by default with ruby since 2.7.0 [as stated here](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/). As sidekiq-scheduler has not been updated to include those gems as explicit dependencies, our projects will fail.

There is already a PR (https://github.com/moove-it/sidekiq-scheduler/pull/299) to change that in `sidekiq-scheduler`, and I poked a little bit to speed things up a little. This update depends on that so I will leave this on hold until we have some more news. 

Two alternative solutions are 1. use the sidekiq-scheduler PR branch as source for the gem in potassium. 2) update to 2.6.5 until this gets fixed. I don't like either so I think waiting is not that bad.

**Comment by blackjid** [comment]
Awesome!

*Juan Ignacio Donoso*

Platanus SpA
