### ISSUE TITLE
Models are not being annotated on initial setup (or after any migration)

### ISSUE THREAD

**Issue by rjherrera** [platanus/potassium#255]
Even though `db:migrate` runs after a project is created (#173), models are not annotated. I tried to run `db:migrate` or `db:migrate:with_data` after creation and it didn't work either. I am not sure what may be the cause for this but it is currently broken. I tested it with both the unreleased rails 6 and also with rails 5.

Maybe @difernandez can enlighten us 😬.

Thanks to @dacasas who also discovered this.

**Comment by difernandez** [comment]
So annotate is not running at all? 😞

In #227 I added code to run `annotate` after `data-migrate` commands. It might be related to that, but if it's not even running for `db:migrate` it might be something else entirely. I'll try to give it a look in the short term

**Comment by rjherrera** [comment]
Not at all 😢 . I started to look and I think that it is related to a breaking change introduced in the [3.0.0 annotate gem version](https://github.com/ctran/annotate_models/blob/develop/CHANGELOG.md#300), in which `'models' => 'true'` has to be set explicitly for annotate to run automatically.

**Comment by difernandez** [comment]
Good finding, sounds like it might be just that. I'll check it out on friday
