### ISSUE TITLE
Tests take too much time

### ISSUE THREAD

**Issue by rjherrera** [platanus/potassium#257]
I think tests are taking too long. I know that we've discussed if the approach for testing is the right one or not, but before doing any major change, I would like to propose 2 changes to make tests more efficient:

1. Change the way we build the project arguments for testing, so that everything is switched off by default, and only the recipe being tested with a real value. This could be _dangerous_ if there are some codependencies between recipes.
2. Change the default test values to the _cheapest_ ones. By default, for example, we execute `webpacker:install` in every step or `active_storage:install`, which are somewhat slow (and unnecesary outside their recipe's spec).

What do you guys think @blackjid @difernandez ?

**Comment by difernandez** [comment]
The first one, like you said, seems like it should be handled more carefully. If we do this we should make sure that a dev working on potassium doesn't need to explicitly add an option to the test project creation that doesn't explicit refer to the recipe being tested.

I think we could start with the second one, sounds like it could have less pitfalls maybe?

**Comment by rjherrera** [comment]
Yes! I tried the second approach and it worked seamlessly. I like it because it is almost the same as the first approach but without the potential pitfalls as you say.

I am also trying something that helps here and in #252, as webpacker is included by default, the `webpacker:install` command, which is very slow, is always executed, regardless of the frontend recipe. The thing is we can pass some flags to rails generation so that it does not execute that command (https://github.com/rails/rails/pull/34071) and as we execute it explicitly on the recipe it would be just fine, and much faster for specs without frontend.

At first we thought that removing some repeated stuff from the webpacker recipe was the way to go, but that means assuming that in every project (even those without frontend!) webpacker would be initialized.
