### ISSUE TITLE
Add arguments to answer inquirer questions

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#29]
The idea is to be able to pre answer the UI question via arguments

```
potassium create --heroku --db mysql --active_admin --paperclip --locale es my_new_app
```

algunos ejemplos...
esto ayudaria bastante para poder correr los test #28

**Comment by juliogarciag** [comment]
@blackjid Qué opinas que es mejor DSL:

1. Envolver la llamada a `Ask` en un método `answer` que cargue la respuesta (`:db`) de las respuestas dadas por la línea de comandos o ejecute el código del bloque (similar a `Hash#fetch`):

```ruby
chosen_database = answer(:db) { Ask.list("Which database are you using?", databases.values) }
```

2. Crear un objeto  en el DSL que haga lo mismo más automágicamente:

```ruby
chosen_database = ask.list(:db, "Which database are you using?", databases.values)
```

Ahora, la segunda es más compleja de implementar (por el uso de metaprogramming) y ese primer argumento no me convence (pero tampoco se me ocurre cómo más pasar el argumento (`--db`) que se va a leer de la línea de comandos). Es más simple y corta para escribir aunque me preocupa que esconda el hecho de que estamos usando inquirer y eso pueda dificultar usarlo. La primera es más verbosa pero me parece que tiene menos drawbacks más allá de su verbosidad.

¿Qué opinas?

**Comment by blackjid** [comment]
creo que tienes razon, es bueno saber que estamos usando inquirer... Hacer un wrapper de eso va a generar un poco de confusion..

creo que me quedo con la opcion 1.
