### ISSUE TITLE
Add PurgeCSS to projects with Tailwind CSS

### ISSUE THREAD

**Issue by gmq** [platanus/potassium#294]
Right now we're including the entirety of Tailwind CSS (78kb gzipped, 603kb uncompressed). They recommend using PurgeCSS to include only the classes that are being used.

https://tailwindcss.com/docs/controlling-file-size#setting-up-purgecss

There may be some difficulty making sure it checks erb and partial files.

**Comment by rjherrera** [comment]
Closing this because it was addressed in #304
