### ISSUE TITLE
El comando falla si la gema inquirer no está instalada previamente

### ISSUE THREAD

**Issue by arturopuente** [platanus/potassium#3]
Agregar inquirer como runtime dependency lo solucionaría me parece.

`/Users/arturo/.rbenv/versions/2.0.0-p643/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- inquirer (LoadError)`

Edit: Aplica también para `gli` y `rails`.

**Comment by juliogarciag** [comment]
El PR asociado soluciona el problema.
