### ISSUE TITLE
Update activeadmin to 2.7

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#300]

**Comment by rjherrera** [comment]
@blackjid Crees que es necesario actualizar explícitamente esto? Actualmente tenemos `~> 2.6` en los gemfiles entonces los proyectos nuevos quedan con 2.7.0 al crearse. Si mal no recuerdo, la idea de poner esa versión era no tener que hacer un update hasta 3.0 revisando los cambios breaking en caso de haberlos

**Comment by blackjid** [comment]
me tinca que no...... :)

**Comment by rjherrera** [comment]
:hypers:
