### ISSUE TITLE
Unnecessary stdout gem

### ISSUE THREAD

**Issue by difernandez** [platanus/potassium#308]
In the heroku recipe we are [adding the rails_stdout_logging gem](https://github.com/platanus/potassium/blob/master/lib/potassium/recipes/heroku.rb#L38). However, this is not necessary since Rails 5, as indicated in [their README](https://github.com/heroku/rails_stdout_logging#rails-5). The code shown there comes by default in the `production.rb` generated by rails generator, and apparently heroku automatically enables `RAILS_LOG_TO_STDOUT`.

The only difference is that by default in a rails generated app `STDOUT.sync = false`, and the `rails_stdout_logging gem` had it set to `true`. This means that Ruby would hold a buffer of logs before writing to standard input, instead of writing immediately. Don't know which we should include though.

**Comment by rjherrera** [comment]
[This](https://stackoverflow.com/questions/29998728/what-stdout-sync-true-means) may help. I think it is not that relevant, but I believe keeping the behaviour we had could be a good idea, as it has worked well so far.

**Comment by difernandez** [comment]
closed in #325
