### ISSUE TITLE
Add new gems in the proper order on manual installs

### ISSUE THREAD

**Issue by jgmontoya** [platanus/potassium#316]
When installing a recipe manually, the added gems are not added in the proper alphabetical order inside the Gemfile.

**Comment by jgmontoya** [comment]
This is a bit more tricky than what I had initially thought.

One approach could be:
1) Read the current project Gemfile and load it into the `gems` var
2) Wipe the Gemfile clean
3) Add the new recipe gems to the var
4) Sort the gems by name
5) Write the Gemfile back

Advantages of this:
Only steps 1) and 2) are missing. Implementing those and adding them at the beginning of the install command would do the trick with 'minimal modification'.

Disadvantages: Reading the Gemfile itself is tricky, as there are multiple ways to specify the gem group. We need to make sure we don't end up breaking the users Gemfile.

A different approach could be to try to figure out the position the new recipe gems need to be inserted and insert them there. This however requires us to make bigger/deeper changes to the way we currently do things (e.g. change the way `gather_gem` works to check for an existing Gemfile and perform the insertion there rather than the usual way).

I'm starting to think this might not be worth it...

@rjherrera any thoughts on this?

**Comment by difernandez** [comment]
I was exploring using `bundle exec rubocop Gemfile -a` to let rubocop do the heavy lifting and sort the file, given a possible violation to `Bundler/OrderedGems`. However, given that the new gems are added after a new line at the end of the file, it doesn't recognize it as a violation, and thus, it doesn't sort.

If there isn't another simple solution, I think it may be too much added complexity for this.

**Comment by rjherrera** [comment]
I forgot to answer, but we had a meeting with @jgmontoya and we saw a couple of alternatives (for example using a tool included in bundler) but they all seemed a bit cumbersome.

I am closing this issue as I agree with what you say regarding the added complexity, and also considering that the "problem" can be manually solved in a couple of seconds by a user adding a recipe.
