### ISSUE TITLE
Add dockerized redis configuration

### ISSUE THREAD

**Issue by jgmontoya** [platanus/potassium#328]
Sidekiq uses redis  which should be dockerized.

We need to add the configuration to the `docker-compose.yml` file and set the env vars to use the docker assigned port (like it's done with the DB [here](https://github.com/platanus/potassium/blob/4aa2414e567d4a524303f9363b6e85a514dff84e/lib/potassium/recipes/database_container.rb#L74)).

[This](https://github.com/platanus/super-cartola/pull/108#issue-532868939) PR might help guide the needed changes.

**Comment by LuisFros** [comment]
You can use this repo where ive done that @jgmontoya  https://github.com/LuisFros/rails-dockerizado
