### ISSUE TITLE
When generated app name is too long, heroku apps might not be created

### ISSUE THREAD

**Issue by difernandez** [platanus/potassium#331]
Heroku's limit for app names is 30 characters. For the production app, counting the prefix `pl-` and the suffix `-production`, there are 14 characters taken, so if the repo name is longer than 16 characters, the app creation will fail. Maybe we should limit it?

**Comment by rjherrera** [comment]
I agree, or at least warn the users about it, seems like a bad surprise to generate a project and then have the heroku part of the generation failing because of the name of the app.
