### ISSUE TITLE
Scout addon gem

### ISSUE THREAD

**Issue by difernandez** [platanus/potassium#348]
Some of our projects use the [Scout heroku addon](https://devcenter.heroku.com/articles/scout) por performance monitoring, [which requires a gem](https://github.com/scoutapp/scout_apm_ruby). Maybe we could add this gem

**Comment by rjherrera** [comment]
I agree we should add this, do you think we should ask the user or just include it without asking?

I'm leaning towards the second option and creating a monitoring or performance recipe that adds this and maybe bullet (#347) but I'm unsure if we should be strongly opinionated and always include them both or let the user decide (with the added overhead of making another decision in the potassium create stage).

**Comment by difernandez** [comment]
Not sure if this is the criteria we've been following, but I think we should let the user decide only on things that are pontentially useful or needed for some projects, but for others it's not, and there isn't too much overhead in determining in which category a new project falls into.

Tbh I haven't really used them much, but it seems to me that Scout/Bullet could be useful for any type of project, so I'm also leaning towards being strongly opinionated.
