### ISSUE TITLE
Give a graphical hint for the heroku dashboard configuration

### ISSUE THREAD

**Issue by agustinf** [platanus/potassium#35]
![screen shot 2016-02-12 at 5 34 38 pm](https://cloud.githubusercontent.com/assets/313750/13019759/fa86c8ca-d1af-11e5-8869-cd2efb5513fa.png)

**Comment by arturopuente** [comment]
@agustinf no nos queda muy claro a qué se refiere esta tarjeta?

**Comment by agustinf** [comment]
Jaja, era sólo un issue para tener la foto hosteada en github
