### ISSUE TITLE
Alias 'vue' imports to 'vue/dist/vue.esm.js'

### ISSUE THREAD

**Issue by iaacosta** [platanus/potassium#359]
Some libraries, such as `vee-validate`, have strange behaviors when some `vue` imports are not aliased to `vue/dist/vue.esm.js`. I think that when `$attrs` is used, there are also some `console` errors.

Should we add this as a default configuration in `config/webpack/environment.js` for the Vue recipe?

```js
environment.config.merge({
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
    },
  },
});
```

**Comment by difernandez** [comment]
closed in #395
