### ISSUE TITLE
Project readme should be updated when potassium install is used

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#38]

**Comment by juliogarciag** [comment]
@blackjid Tengo una duda: ¿Cómo nos aseguramos de no estar editando lo que alguien ha escrito de forma manual en algún momento?

**Comment by blackjid** [comment]
Yo creo que siempre luego correr install uno debiera revisar revisar el git diff.
Y dejar a responsabilidad del usuario que cambios se hicieron
