### ISSUE TITLE
LoadError sassc file from github sass/sassc-ruby gem

### ISSUE THREAD

**Issue by micostabal** [platanus/potassium#442]
Hi! I'm having the following issue when I try to create a project with platanus config. After I complete the bundle I'm getting:

```
/.rvm/gems/ruby-2.7.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- sassc (LoadError)
error: exit
```
This might be related to a recent change last month in commit 2299250, (I'm not sure though): 
```
gather_gem("sassc", github: "sass/sassc-ruby", ref: 'refs/pull/233/head')
```
Anyways, I would appreciate any help I can get.

Thank you very much!

**Comment by difernandez** [comment]
Are you using the latest version of the gem, or potassium from master? I think the commit you linked was in fact made to fix that issue (see https://github.com/platanus/potassium/pull/436 for details), but that commit hasn't been included in a released version in rubygems.
If you are using the gem, could you try cloning the repo to your computer and running it from there with something like `./potassium/bin/create <project-name> --platanus-config`? I think that would solve your issue for now, let me know

**Comment by micostabal** [comment]
Of course! I tried what you just said and went through perfectly! Thank you
