### ISSUE TITLE
Potassium install command fails

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#52]
In the a80c4d9d4b57619cf36f807b5bde75af9ec9585c commit stop working.

```
potassium install
Select a recipe to install: admin
error: undefined method `cli_options' for Potassium::RecipeGenerator:Class
```

**Comment by blackjid** [comment]
@juliogarciag alguna idea??
@ldlsegovia @emilioeduardob?? tal vez vieron algo cuando empezadon a jugar con el readme?? o no estaba mergeado ese commit todavia?

**Comment by juliogarciag** [comment]
@blackjid Oh, creo que ya entendí. Esas `cli_options` son para obtener las opciones pasadas por línea de comando. Las agregué en [el generador de la app](http://github.com/platanus/potassium/blob/master/lib/potassium/templates/application/generator.rb#L8) pero no en el generador para la instalación. 

Recuerdo que sólo lo agregue en ese generador y no en el de `install` porque no logré agregar la config. de GLI para ambos a pesar que usé lo que indicaba la documentación. Como no me pareció tan malo que `install` no recibiera esos argumentos, seguí avanzando y olvidé que los asks se ejecutaban igualmente en `install`. 

Cambiar `set(:answers, extract_answers(self.class.cli_options))` por `set(:answers, extract_answers(self.class.cli_options || {}))` en [answer-helpers](https://github.com/platanus/potassium/blob/master/lib/potassium/templates/application/helpers/answer-helpers.rb), y luego agregar algo así:

```
# ...
class RecipeGenerator < Rails::Generators::NamedBase
  class << self
    attr_accessor :cli_options
  end
  # ...
end
```

en [el generador de install](https://github.com/platanus/potassium/blob/master/lib/potassium/templates/application/recipe_generator.rb) deberían solucionar el problema.

**Comment by blackjid** [comment]
Ok, gracias julio...
creo que hay que darle una vuelta a el comando `install` voy a hacer un issue para comentar sobre eso

**Comment by blackjid** [comment]
fixed in #55
