### ISSUE TITLE
Command install not always useful

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#53]
El comando install a veces no funciona muy bien porque no se tiene el contexto de las respuestas a las preguntas que se hicieron cuando se corre potassium...

Por ejemplo quise hacer `potassium install ci` para installar continuous integration en otro projecto, pero esa recipe depende de que se haya contestado que `si` a `Do you want to deploy with heroku`. Entonces no hace nada.

Si le saco la dependencia a `heroku` tambien tengo problemas porque depende de saber que DB se eligio... y asi..

No creo que sea el unico caso....

@platanus/developers

**Comment by ldlsegovia** [comment]
@blackjid te parece que sería mejor hacer una whitelist con las recetas que se pueden usar con `install` o qué propones como solución?

**Comment by blackjid** [comment]
me parece buena idea hacer un whitlist, porque no siempre tiene sentido hacer install.
Pero tambien me gustaria hacer algo para que sea mas inteligente...

Por ejemplo, de alguna manera poder inferir las respuestas a partir de un projecto. (gema instalada, archivo existente, etc) para poder usar esos datos en la ejecucion de un recipe...

Tambien podriamos ver como definir dependencias. En el caso de dije antes, me hace sentido que heroku y ci se instalen juntas, pero estan definidas como recetas diferentes...

Tal vez podrian haber una receta que incluye las otras dos y esa es la que se llama en el templata y en el install...

**Comment by ldlsegovia** [comment]
Para mi hay un problema con el `install` y es que lo estamos forzando al ciclo de vida del `create`. Por ej:

La receta `admin` en el `create`:

- Si `admin_mode`
  - Si `authentication = devise`
    - instala la gema
    - after `gem_install`, corre el generador: `active_admin:install` y se modifican los archivos generados por el install.
    - (En el paso anterior se genera una acción `admin_install`, para después permitir agregar un callback para ejecutar algo después de la instalación. Como es el caso de la receta `angular_admin`)
  - Si no, muestra mensaje: "te falta devise"

Actualmente, el `install` está suponiendo que esas preguntas ( Si `admin_mode` y Si `authentication = devise`) son true, luego hace bundle (no veo que haga migrate) y luego fuerza los callbacks que puede haber generado la receta. Esto para mi trae problemas:

1. Es poco intuitivo. Es decir, debemos saber exactamente de que está compuesta la receta que queremos correr para asegurarnos que esos `true` de las preguntas, son realmente `true`
2. Nos obliga un poco a seguir un flujo (el del create) que no es el que se da en la instalación.

De esto, se me ocurre que el `install` debería ser:

- Si está instalado devise
  - instala la gema
  - after `gem_install`, corre el generador: `active_admin:install` y se modifican los archivos generados por el install.
- Si no, muestra mensaje: "te falta devise"

**Como solución se me ocurre:**

Sacar lo que el `create` y el `install` tienen en común. Es decir, las acciones pero no ligadas a los callbacks. Por decir algo (no estoy seguro de la implementación), un modulo `Admin` con `Admin.add_gem`, `Admin.install`
Habiendo sacado lo común a otro archivo, podemos tener ahora dos recetas: create/admin y install/admin.

En la primera:

- Si `admin_mode`
  - Si `authentication = devise`
    - `Admin.add_gem`
    - after `gem_install`, `Admin.install`
    - se genera una acción `admin_install`
  - Si no, muestra mensaje: "te falta devise"

En la segunda:

- Si está instalado devise
  - `Admin.add_gem`
  - after `gem_install`, `Admin.install`
- Si no, muestra mensaje: "debes instalar devise primero"

**Las ventajas:**

- No es obligatorio tener las mismas recetas para `create` que para `install` (whitelist)
- Se diferencia el flujo. En el `create`, se va recordando lo que se eligió para determinar que instalar, en el en `install` corremos código distinto para ver si tenemos las dependencias necesarias (Mirando el Gemfile, como dice @blackjid)
- En el `install` no tenemos manejo complejo de dependencias. Es decir, si de mirar el `Gemfile` por ej, descubrimos que una dependencia no está instalada, mostramos mensaje de error animando al usuario a instalar esa primero. De esta manera, para instalar la receta `angular_admin` por ej, no dependeríamos del callback `admin_install` ya que, si estamos pudiendo correr esta receta, active admin ya debe estar instalado.

Qué les parece?

**Comment by blackjid** [comment]
fixed in #55
