### ISSUE TITLE
run the setup script with existing db

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#71]
if we run `bin/setup` on an existing project, it fails because `rake db:setup` fails on existing database

**Comment by juliogarciag** [comment]
mmm...  se supone que `rake db:migrate` crea, si no hay, una tabla de migraciones que se revisa precisamente para saber qué migraciones correr sobre una base de datos. En ese sentido, `rake db:migrate` no debería provocar errores al menos que la base de datos sobre la que se actúa no haya sido creada/migrada usando rails.

**Comment by blackjid** [comment]
mm, @juliogarciag me equivoque, en el setup se corre `rake db:setup`. eso es lo que falla cuando ya existe. (lo edite en el primer comentario)

**Comment by juliogarciag** [comment]
Ah, entonces lo que falla es el `rake db:create`?
