### ISSUE TITLE
Add shoulda-matchers config to rails_helper

### ISSUE THREAD

**Issue by arturopuente** [platanus/potassium#80]
This is missing at the end of rails_helper

```ruby
Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

**Comment by blackjid** [comment]
What is it for?

**Comment by arturopuente** [comment]
@blackjid we found out the new major release of `shoulda-matchers` doesn't work out of the box with the Rails/Rspec combo (!) we need to tell it we're working with both Rails and Rspec, everything else (specs and config) remains the same.
