### ISSUE TITLE
Include quiet assets gem

### ISSUE THREAD

**Issue by arturopuente** [platanus/potassium#81]
https://github.com/evrone/quiet_assets

**Comment by blackjid** [comment]
@ldlsegovia estaba pensando donde agregar esto en potassium, debiera ser super simple, pero me surgio la una duda. 

Debieras ser algo como 

```
gather_gems(:development, :test) do
    gather_gem 'rack-timeout'
end
```

Pero donde lo pongo?? creo una recipe `quiet-assets` que hace eso nomas???? y cuando queramos agregar `annotate`?? otro recipe??? Como que no cierto?

Me bajo la duda si la estrucura con que esta potassium estara bien..

Tal vez el caso de `quiet assets` debiera ir en un recipe `development`, pero efectivamente algo como `paperclip` si tiene sentido que tenga una receta propia, porque hace una serie de configuraciones que podemos aprovechar como estandar platanus. Para quiet assets lo unico del estandar, es usarla...

No se si me explico...

Alguna idea??

**Comment by arturopuente** [comment]
@blackjid @ldlsegovia yo creo que debería en un recipe de `development_tools`, donde pondríamos gemas que usamos en todos los proyectos y que mejoran la experiencia de desarrollo (se me ocurre incluir `better_errors` en ese recipe también)

**Comment by ldlsegovia** [comment]
@blackjid pienso que tenemos agrupaciones caprichosas en las recetas. Los criterios de agrupación en testing, paperclip o cleanup son bien distintos pero me parece bien. Creo que está buena esa flexibilidad ya que en potassium hacemos cosas de naturaleza bastante variada y por ahí estructurar más nos va a hacer perder claridad. Por ej: con testing, a mi me hace sentido que `rspec`, `guard` y los installers relacionados se hagan en una misma receta. Yo creo que el criterio de agrupación debe ser **el que hace sentido para lo que se está agregando** (teniendo en cuenta si es una receta que debería ser instalable luego). A mi me preocupa más que tener muchas recetas, la relación de dependencia entre ellas. Por eso, en algún momento planteé que pasáramos parámetros entre las recetas. Cosa que si B necesita de A, nunca ejecutemos B antes que A.

Para esto en particular, yo creo que me hace sentido tener una sola receta que sea `gemfile` o `gemfile_base` que tenga, a diferencia de lo que propone @arturopuente, todas las gemas de todos los ambientes que simplemente necesitan estar ahí y no corren ningún instalador ni hacen nada especial.

**Comment by blackjid** [comment]
a mi me parece bien tener un gemfile base, de hecho casi que podria estar en los `assets/Gemfile` y luego sobre eso usar `gather_gem` para complementar

@arturopuente ?

**Comment by arturopuente** [comment]
@blackjid @ldlsegovia sí, apoyo la moción de tener una receta de Gemfile. El overhead de incluir todas las gemas que usamos es mínimo.
