### ISSUE TITLE
remove staging environment

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#87]
Pensaba que era una buena idea tener un environment staging, pero luego de leer un poco mas, empieza a tener sentido que tratemos de forzar lo mas posible que staging y production sean igual. Y tener un environment aparte nos invita a configurar cosas de manera diferente.

https://devcenter.heroku.com/articles/multiple-environments
https://devcenter.heroku.com/articles/development-configuration#configuration

Algunas discuciones en suspenders
https://github.com/thoughtbot/suspenders/issues/506
https://github.com/thoughtbot/suspenders/pull/743/files

**Comment by blackjid** [comment]
Por ahora no estabamos haciendo nada diferente en staging, asique no debiera molestar mucho

**Comment by blackjid** [comment]
thoughts??
cc: @platanus/developers

**Comment by arturopuente** [comment]
@blackjid me parece que sí, deberíamos tratar nuestro ambiente de staging como si fuera production lo más posible.

**Comment by blackjid** [comment]
algun otro 👍 ??
