### ISSUE TITLE
improve the way the gemfile is defined

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#90]
This comes from this discussion https://github.com/platanus/potassium/issues/81#issuecomment-216383634

**Comment by arturopuente** [comment]
@blackjid @ldsegovia

Actualmente tenemos un template `application` que se encarga de crear el Gemfile en base a las preguntas y recetas que hemos seleccionado. Esto por consenso lo vamos a cambiar a una sola receta, y luego, en vez del bloque de preguntas para definir qué recetas quiere el usuario, éstas se van a cargar posteriormente mediante el comando `install`.

Ahora bien, tengo una duda con respecto a cómo organizar el código con este approach:

1) Deberíamos reutilizar la estructura que ya tenemos, y setear las respuestas a las gemas por defecto y dejar que el instalador siga el flujo normalmente, con las recetas dependiendo de la selección de preguntas o

2) Modificar las recetas para que se ejecuten al llamarlas y no sea necesario configurar las preguntas. Por ejemplo, el create de ActiveAdmin:

```ruby
def create
  if selected?(:admin_mode)
    if selected?(:authentication)
      add_active_admin
    else
      info "ActiveAdmin can't be installed because Devise isn't enabled."
    end
  end
end
```

Pasaría a esto:

```ruby
def create
  add_active_admin
end
```

Me decantaría por la segunda opción, porque me parece que el código queda más limpio y ordenado al no tener tantos caminos posibles, pero quisiera ver si hay otros puntos de vista o si las preguntas por ahí tienen un valor adicional que no he considerado.

**Comment by blackjid** [comment]
@arturopuente, por como veo que suspenders esta avanzando creo que me gusta mucho.
Creo que es mucho mas simple y mantenible. Hasta @bunzli podria hacer un generador...

En estos dos PR discuten (desde hace mas de 1 año como hacer para que suspender tenga lo que tenemos nosotros en con `potassium install` pero me gusta mas su approach.

https://github.com/thoughtbot/suspenders/pull/676
https://github.com/thoughtbot/suspenders/pull/511

estemos atentos,

**Comment by hidalgoegz** [comment]
Esto llego a ser solventado? o se desea solucionar?

**Comment by blackjid** [comment]
nop, matemoslo no mas..
