### ISSUE TITLE
refactor potassium to extend suspenders

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#97]
The idea would be to extend suspenders instead of building everything.

Why: 
- Most of the ideas and opinions and potassium setup are taken from suspenders. Where there are extensive experience and discussion about how it should evolve.
- Most of the time we ARE comfortable with suspenders opinions
- Suspenders is being refactored in a way that will allow us to extend it in a simple way and only choose the bits that we like.
- It will be more maintainable and easy to extend
- We can keep doing the potassium bits that we like

How would it work:

The idea es now to include suspenders and potassium in the `Gemfile` of the project.

```
gem 'suspenders'
gem 'potassium'
```

this will add generators, that you can call like this

```
rails g suspenders:segment
rails g potassium:api
rails g potassium:heroku
```

We can keep running a set of generators when we call `potassium create`

This will take time because in suspenders they are starting to split the big main generator in a per-feature generator.

These are some related issues and prs on suspenders
- https://github.com/thoughtbot/suspenders/pull/511
- https://github.com/thoughtbot/suspenders/pull/767
- https://github.com/thoughtbot/suspenders/pull/676

**Comment by hidalgoegz** [comment]
@blackjid lo voy a cerrar
